kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      replicas: 1
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  
  alertmanager:
    enabled: false
  
  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.2.211
    extraSecretMounts:
      - name: grafana-tls
        secretName: grafana-tls
        defaultMode: 0440
        mountPath: /etc/grafana/certs
        readOnly: true
    grafana.ini:
      server:
        protocol: https
        cert_file: /etc/grafana/certs/tls.crt
        cert_key: /etc/grafana/certs/tls.key
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTPS
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
        scheme: HTTPS
    persistence:
      enabled: true
      size: 2Gi
