apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "-180"
spec:
  description: Monitoring Project
  sourceRepos:
    - https://github.com/nickkostov/*
    - ghcr.io/nickkostov
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'