argo-cd:
  global:
    domain: argocd.range.local
  
  redis:
    enabled: true
    
  redis-secret-init:
    enabled: false
  
  server:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.2.210
    certificate:
      enabled: true
      domain: argocd.range.local
      issuer:
        kind: ClusterIssuer
        name: ca-issuer
    ingress:
      enabled: false
  
  configs:
    params:
      server.insecure: false
    cm:
      accounts.dipmon: login,apiKey
      admin.enabled: true
      create: true
      exec.enabled: true
      url: https://argocd.range.local
