---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgCOQNza5kl/JnMt+pfuh0Gzj1WFCYCk3ip/2dn2T3wirLBcXBU5BvEq5ZMOIyB42DasQkMsmwCnw2VGMmnQ7PgjkJwtmBXqCK1uLNMk29zC4O/2uYONqRCNe1DlflwgBw2FHEkCjPPwSjqYORytccWejOPcyiUPReG3usZgcoLkF4VE1VvNFEjhauJFSM/W7efil5RbFsmAu5IrtseZ5FupDgBOofBwfvHaK5zTJrLFY8zw4awTBhAblbnqb4pnvNX/HKLYrLSlx4wCU5vak0SJ/OAtaZMF2D/neXVWccpGsRLw6PJEakU7o4quzjwsw6Xo/MynvZmdbuohpLcRmKcFh6DdOs4oei0xkh6ICdRUa9BL2SxhsVQ2KqcwBPIpsrad5i/v8XHq5v/N+LDzyyLU1f5YXm3LF4mk9CgM6EP0YYl+fPFohMbGevydyEpVUONANr3qM5ikDuEO/3XokXlJfzf8ZOwG0s7FtLRDkY6wRQrlHq8AbpLeZV7fmFA+hll3N/sn2EJixJXeIVgI7Pefs7siNX/fYUXIbbtMfODqnTKVVypm5tMoDbImhvkrojAoH/iYXmzEcxeT6IIwIaglkqt2ZN8lND9IbSoIPljvu2A5qHcRbv4ui6LAYvUB3Y1rAC5iUcjnTEZXrf63EdLyWO3464uefzfQXUaqao3Et+6Wqh47wk7heHxGC3jLncR0bkMPXhaYbjbev6m1oVNuT66Fetp1QQc2kER+LaaRv8OmTWnQDGmkClo4dgCB01aiV+fy0eqh62g41sKtj2QSrQOws5mTngDUhvRHiwii0EtuKTw3CvpVqYScFKKQMjZG763gciu/hsR6U+9LOk2yW/8Ubyp069a+
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
