apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Development Apps Project
  sourceRepos:
    - https://github.com/nickkostov/homelab
    - https://github.com/nickkostov/*
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
