apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
spec:
  project: middleware
  source:
    repoURL: https://github.com/nickkostov/homelab
    path: clusters/homelab/manifests/middleware/openwebui/ui
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true