apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-deployed.teams: planet-portal
    notifications.argoproj.io/subscribe.on-sync-failed.teams: planet-portal
    notifications.argoproj.io/subscribe.on-health-degraded.teams: planet-portal
    notifications.argoproj.io/subscribe.on-sync-status-unknown.teams: planet-portal
    notifications.argoproj.io/subscribe.on-sync-running.teams: planet-portal
spec:
  project: middleware
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.28.1
      helm:
        valueFiles:
          - $values/clusters/homelab/manifests/middleware/vault/chart/values.yaml
    - repoURL: https://github.com/nickkostov/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/nickkostov/homelab
      targetRevision: HEAD
      path: clusters/homelab/manifests/middleware/vault/chart/
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true