server:
  enabled: true
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/tls/tls.crt"
        tls_key_file = "/vault/tls/tls.key"
      }
      storage "raft" {
        path = "/vault/data"
      }
  ha:
    enabled: false
  extraVolumes:
    - type: secret
      name: vault-tls
      path: /vault/tls
  service:
    type: LoadBalancer
    port: 443
    targetPort: 8200
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.2.204

ui:
  enabled: true
  serviceType: ClusterIP

injector:
  enabled: false