server:
  enabled: true
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.2.204

ui:
  enabled: true
  serviceType: LoadBalancer
  loadBalancerIP: 192.168.2.204

injector:
  enabled: false